---
name: Python Tests

"on":
  pull_request:
    paths:
      - .github/workflows/python-tests.yaml
      - "**/*.py"
      - pyproject.toml
      - uv.lock
  push:
    branches:
      - main
    paths:
      - .github/workflows/python-tests.yaml
      - "**/*.py"
      - pyproject.toml
      - uv.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  run_unit_tests:
    name: "Unit tests"
    permissions:
      contents: read
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.26"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Set up Python
        run: uv python install

      - name: Install Project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests
